#service port
server:
  port: 8080

#register with eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost


#routes service
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**

        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/courses/**
